openapi: 3.0.3
info:
  title: Related Visitors API
  description: >
    Use this API to unify and personalize the experience for your anonymous
    users who visit your website from regular and in-app browsers.
  version: '1.0'
  contact:
    name: Fingerprint Support
    email: support@fingerprint.com
tags:
  - name: Related Visitors
    description: >
      Find visitor IDs that originated from a different browser on the same
      mobile device.
servers:
  - url: https://api.fpjs.io
    description: Recommended if your customer base is primarily in the Americas.
  - url: https://eu.api.fpjs.io
    description: Recommended if your customer base is primarily in Europe.
  - url: https://ap.api.fpjs.io
    description: Recommended if your customer base is primarily in the APAC region.
security:
  - ApiKeyHeader: []
  - ApiKeyQuery: []
paths:
  /related-visitors:
    get:
      tags:
        - Related Visitors
      operationId: getRelatedVisitors
      summary: Get Related Visitors
      description: >
        This API will enable you to find if one or more web and in-app browser
        sessions originated from the same mobile device.

        When requested, this API will search identification events within the
        past 6 months to find the visitor IDs that belong to the same mobile
        device as the given visitor ID.

        Please visit the
        [Overview](https://dev.fingerprint.com/reference/related-visitors-api)
        page to learn more about this API.
      parameters:
        - name: visitor_id
          description: >-
            The [visitor
            ID](https://dev.fingerprint.com/docs/js-agent#visitorid) for which
            you want to find the other visitor IDs that originated from the same
            mobile device.
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelatedVisitorsResponse'
              examples:
                200-success-empty-response:
                  summary: Success, empty response
                  value:
                    relatedVisitors: []
                200-success-response:
                  summary: Success response
                  value:
                    relatedVisitors:
                      - visitorId: NtCUJGceWX9RpvSbhvOm
                      - visitorId: 25ee02iZwGxeyT0jMNkZ
        '400':
          description: >-
            Bad request. The visitor ID parameter is missing or in the wrong
            format.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorVisitor400Response'
              examples:
                400-empty-visitor-id:
                  summary: >-
                    Error response when the request does not include a visitor
                    ID
                  value:
                    error:
                      code: RequestCannotBeParsed
                      message: visitor id is required
                400-invalid-visitor-id:
                  summary: Error response when the visitor ID is incorrectly formatted
                  value:
                    error:
                      code: RequestCannotBeParsed
                      message: invalid visitor id
        '403':
          description: Forbidden. Access to this API is denied.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCommon403Response'
              examples:
                403-feature-not-enabled:
                  summary: >-
                    Error response when this feature is not enabled for a
                    subscription.
                  value:
                    error:
                      code: FeatureNotEnabled
                      message: feature not enabled
                403-token-not-found:
                  summary: >-
                    Error response when the provided secret API key does not
                    exist.
                  value:
                    error:
                      code: TokenNotFound
                      message: secret key is not found
                403-token-required:
                  summary: Error response when the secret API key was not provided.
                  value:
                    error:
                      code: TokenRequired
                      message: secret key is required
                403-wrong-region:
                  summary: >-
                    Error response when the API region is different from the
                    region, the calling application is configured with.
                  value:
                    error:
                      code: WrongRegion
                      message: wrong region
        '404':
          description: >-
            Not found. The visitor ID cannot be found in this application's
            data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorVisitor404Response'
              examples:
                404-visitor-not-found:
                  summary: >-
                    Error response when the visitor ID cannot be found in this
                    application's data.
                  value:
                    error:
                      code: VisitorNotFound
                      message: visitor not found
        '429':
          description: Too Many Requests. The request is throttled.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCommon429Response'
              examples:
                example:
                  summary: Too Many Requests
                  value:
                    error:
                      code: TooManyRequests
                      message: too many requests
components:
  securitySchemes:
    ApiKeyHeader:
      type: apiKey
      in: header
      name: Auth-API-Key
    ApiKeyQuery:
      type: apiKey
      in: query
      name: api_key
  schemas:
    RelatedVisitor:
      type: object
      additionalProperties: false
      properties:
        visitorId:
          description: >-
            Visitor ID of a browser that originates from the same mobile device
            as the input visitor ID.
          type: string
          example: Ibk1527CUFmcnjLwIs4A
      required:
        - visitorId
    RelatedVisitorsResponse:
      type: object
      additionalProperties: false
      properties:
        relatedVisitors:
          type: array
          items:
            $ref: '#/components/schemas/RelatedVisitor'
      required:
        - relatedVisitors
    ErrorVisitor400Response:
      type: object
      additionalProperties: false
      properties:
        error:
          type: object
          additionalProperties: false
          properties:
            code:
              type: string
              description: >
                Error code: * `RequestCannotBeParsed` - The visitor ID parameter
                is missing or in the wrong format.
              enum:
                - RequestCannotBeParsed
              example: RequestCannotBeParsed
            message:
              type: string
              example: invalid visitor id
          required:
            - code
            - message
    ErrorCommon403Response:
      type: object
      additionalProperties: false
      properties:
        error:
          type: object
          additionalProperties: false
          title: Common403ErrorResponse
          properties:
            code:
              type: string
              description: |
                Error code:
                 * `TokenRequired` - `Auth-API-Key` header is missing or empty
                 * `TokenNotFound` - No Fingerprint application found for specified secret key
                 * `SubscriptionNotActive` - Fingerprint application is not active
                 * `WrongRegion` - server and application region differ
                 * `FeatureNotEnabled` - this feature (for example, Delete API) is not enabled for your application
              enum:
                - TokenRequired
                - TokenNotFound
                - SubscriptionNotActive
                - WrongRegion
                - FeatureNotEnabled
              example: TokenRequired
            message:
              type: string
              example: secret key is required
          required:
            - code
            - message
    ErrorVisitor404Response:
      type: object
      additionalProperties: false
      properties:
        error:
          type: object
          additionalProperties: false
          title: ErrorVisitor404ResponseError
          properties:
            code:
              type: string
              description: >
                Error code: * `VisitorNotFound` - The specified visitor ID was
                not found. It never existed or it may have already been deleted.
              enum:
                - VisitorNotFound
              example: VisitorNotFound
            message:
              type: string
              example: visitor not found
          required:
            - code
            - message
    ErrorCommon429Response:
      type: object
      additionalProperties: false
      properties:
        error:
          type: object
          additionalProperties: false
          properties:
            code:
              type: string
              description: |
                Error code: * `TooManyRequests` - The request is throttled.
              enum:
                - TooManyRequests
              example: TooManyRequests
            message:
              type: string
              example: request throttled
          required:
            - code
            - message
